#!/usr/bin/env bash
# session-start.sh
# Runs at session start. Pre-computes wiki health and writes _status.md.
# Hook type: UserPromptSubmit (Claude Code)

set -euo pipefail

# ── Resolve paths ─────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$SCRIPT_DIR/../scripts"

WIKI="${WIKI_PATH:-$HOME/llm-wiki-pm/wiki}"

# ① Exit silently if wiki not initialized yet
if [[ ! -d "$WIKI" ]]; then
  exit 0
fi

# ── Gather timestamps ──────────────────────────────────────────────────────────
NOW_TS=$(date +%s)
NOW_FMT=$(date '+%Y-%m-%d %H:%M')
THRESHOLD_STALE=$(( NOW_TS - 30 * 86400 ))
THRESHOLD_DECAY=$(( NOW_TS - 60 * 86400 ))

# ② Run lint and capture JSON output
LINT_OUTPUT=""
BROKEN_LINKS=0
ORPHANS=0

if [[ -f "$SCRIPTS_DIR/lint.py" ]]; then
  # Try --quiet --json first; fall back to plain run
  if LINT_OUTPUT=$(python3 "$SCRIPTS_DIR/lint.py" "$WIKI" --quiet --json 2>/dev/null); then
    BROKEN_LINKS=$(echo "$LINT_OUTPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(len(d.get('broken_links', [])))" 2>/dev/null || echo 0)
    ORPHANS=$(echo "$LINT_OUTPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(len(d.get('orphans', [])))" 2>/dev/null || echo 0)
  else
    LINT_OUTPUT=$(python3 "$SCRIPTS_DIR/lint.py" "$WIKI" 2>&1 || true)
    BROKEN_LINKS=$(echo "$LINT_OUTPUT" | grep -c 'broken link' 2>/dev/null || echo 0)
    ORPHANS=$(echo "$LINT_OUTPUT" | grep -c 'orphan' 2>/dev/null || echo 0)
  fi
fi

# ③ Scan for stale pages (updated: > 30 days old)
STALE_PAGES=()
DECAY_PAGES=()

scan_dir() {
  local dir="$1"
  [[ -d "$WIKI/$dir" ]] || return
  while IFS= read -r -d '' file; do
    local slug
    slug=$(basename "$file" .md)

    # Extract updated: frontmatter value
    local updated_val
    updated_val=$(grep -m1 '^updated:' "$file" 2>/dev/null | sed 's/updated:[[:space:]]*//' | tr -d '"' | xargs || true)
    [[ -z "$updated_val" ]] && continue

    # Convert date to epoch (GNU date)
    local updated_ts
    updated_ts=$(date -d "$updated_val" +%s 2>/dev/null || echo 0)
    [[ "$updated_ts" -eq 0 ]] && continue

    if [[ "$updated_ts" -lt "$THRESHOLD_STALE" ]]; then
      STALE_PAGES+=("$dir/$slug ($updated_val)")
    fi

    # Check competitive tag for decay
    if grep -q 'competitive' "$file" 2>/dev/null && [[ "$updated_ts" -lt "$THRESHOLD_DECAY" ]]; then
      DECAY_PAGES+=("$dir/$slug ($updated_val)")
    fi
  done < <(find "$WIKI/$dir" -maxdepth 1 -name '*.md' -print0 2>/dev/null)
}

for d in entities concepts comparisons; do
  scan_dir "$d"
done

STALE_COUNT="${#STALE_PAGES[@]}"
DECAY_COUNT="${#DECAY_PAGES[@]}"

# ④ Write _status.md
STATUS_FILE="$WIKI/_status.md"

{
  echo "# Wiki Status"
  echo ""
  echo "Last checked: $NOW_FMT"
  echo ""
  echo "## Health Summary"
  echo ""
  echo "| Metric | Count |"
  echo "|--------|-------|"
  echo "| Broken links | $BROKEN_LINKS |"
  echo "| Orphan pages | $ORPHANS |"
  echo "| Stale pages (>30 days) | $STALE_COUNT |"
  echo "| Confidence decay candidates (>60 days, competitive) | $DECAY_COUNT |"
  echo ""

  if [[ "$DECAY_COUNT" -gt 0 ]]; then
    echo "## Confidence Decay Candidates"
    echo ""
    echo "These competitive pages have not been updated in over 60 days."
    echo "Consider re-verifying claims or lowering confidence scores."
    echo ""
    for p in "${DECAY_PAGES[@]}"; do
      echo "- $p"
    done
    echo ""
  fi

  if [[ "$STALE_COUNT" -gt 0 ]]; then
    echo "## Stale Pages"
    echo ""
    echo "Pages with updated: frontmatter older than 30 days."
    echo ""
    for p in "${STALE_PAGES[@]}"; do
      echo "- $p"
    done
    echo ""
  fi

  if [[ -n "$LINT_OUTPUT" && "$BROKEN_LINKS" -gt 0 ]]; then
    echo "## Lint Details"
    echo ""
    echo '```'
    echo "$LINT_OUTPUT" | head -50
    echo '```'
    echo ""
  fi

  echo "---"
  echo "*Generated by session-start.sh. Do not edit manually.*"
} > "$STATUS_FILE"

# ⑤ Print one-line summary to stderr
TOTAL_ISSUES=$(( BROKEN_LINKS + ORPHANS + STALE_COUNT + DECAY_COUNT ))
echo "Wiki health: $TOTAL_ISSUES issues found. See _status.md" >&2

exit 0
